version: "3.7"
services:
  redis:
    image: redis:6.0.6-alpine

  mongodb:
    image: mongo:4.4.0
    restart: always

  app:
    build: ./
    depends_on:
      - mongodb
      - redis
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://mongodb:27017/movies
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 3000
    command: npm run start
